# Скрытые марковские модели

## Библиотеки

In [1]:
import re

import urllib
import numpy as np
import nltk
from nltk.tag import hmm
from nltk.corpus import brown
import pandas as pd

from collections import Counter

import nltk.lm as lm
from nltk.util import ngrams as nltk_ngrams
import numpy as np
import scipy.stats as st

from nltk.tokenize import RegexpTokenizer

## Brown Dataset HMM

### Dataset

In [2]:
nltk.download('brown')
english = re.compile('^[a-z]+$')

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.

In [3]:
tokens = []
for sent in brown.sents():
    for w in sent:
        w = w.lower()
        if english.match(w):
                tokens.append(w)
print(f'Number of tokens: {len(tokens)}')

Number of tokens: 981716

In [4]:
text = ' '.join(tokens)
len(text), text[:100]

(5579335,
 'the fulton county grand jury said friday an investigation of recent primary election produced no evi')

### Unsupervised обучение скрытой марковской модели (Алгоритм Баума-Велша)

In [5]:
vocab = sorted(list(set(text)))
len(vocab)

27

In [6]:
trainer = hmm.HiddenMarkovModelTrainer(range(2), vocab)

In [7]:
tagger = trainer.train_unsupervised([text[:5000]], max_iterations=50)

iteration 0 logprob -24426.657272880882
iteration 1 logprob -20557.394505817527
iteration 2 logprob -20557.35237670552
iteration 3 logprob -20557.303236543463
iteration 4 logprob -20557.245522467314
iteration 5 logprob -20557.177381579364
iteration 6 logprob -20557.096596537358
iteration 7 logprob -20557.000494209296
iteration 8 logprob -20556.885832288535
iteration 9 logprob -20556.74865751582
iteration 10 logprob -20556.584126998274
iteration 11 logprob -20556.386281830386
iteration 12 logprob -20556.14775879927
iteration 13 logprob -20555.85942157268
iteration 14 logprob -20555.509887262106
iteration 15 logprob -20555.084916898435
iteration 16 logprob -20554.566629303925
iteration 17 logprob -20553.93248684055
iteration 18 logprob -20553.1539888181
iteration 19 logprob -20552.194995092137
iteration 20 logprob -20551.009591678212
iteration 21 logprob -20549.539406726515
iteration 22 logprob -20547.71029896083
iteration 23 logprob -20545.428383615556
iteration 24 logprob -20542.575443752
iteration 25 logprob -20539.00388669498
iteration 26 logprob -20534.53145956075
iteration 27 logprob -20528.935662340788
iteration 28 logprob -20521.94655192912
iteration 29 logprob -20513.233257680255
iteration 30 logprob -20502.37261210499
iteration 31 logprob -20488.777828078786
iteration 32 logprob -20471.557737785097
iteration 33 logprob -20449.29935575401
iteration 34 logprob -20419.887320151112
iteration 35 logprob -20380.773572478894
iteration 36 logprob -20330.42991420501
iteration 37 logprob -20271.25065918197
iteration 38 logprob -20211.26137112116
iteration 39 logprob -20159.695906150748
iteration 40 logprob -20120.558630269832
iteration 41 logprob -20092.465496085693
iteration 42 logprob -20072.165155281098
iteration 43 logprob -20056.897707086297
iteration 44 logprob -20044.887544912206
iteration 45 logprob -20035.07096944471
iteration 46 logprob -20026.78604315021
iteration 47 logprob -20019.586080366935
iteration 48 logprob -20013.149411169114
iteration 49 logprob -20007.239502898534

#### Исследуем полученную модель

Матрица переходов $$\{a_{ij} = p(s_j|s_i)\}_{i,j = 1}^{|S|}$$

In [8]:
trans_matr = pd.DataFrame(
    data=np.array([
        [2 ** log_p for log_p in tagger._transitions[0]._data],
        [2 ** log_p for log_p in tagger._transitions[1]._data]
    ]),
    columns=[0, 1],
    index=[0, 1])
trans_matr

          0         1
0  0.342254  0.657746
1  0.885628  0.114372

Матрица выходных вероятностей $$\{ b_{ij} = p(x_j|s_i) \}_{i, j = 1}^{|S|, |X|}$$

In [9]:
out_matr = pd.DataFrame(
    data=np.array([
        [2 ** log_p for log_p in tagger._outputs[0]._data],
        [2 ** log_p for log_p in tagger._outputs[1]._data]
    ]),
    index=[0, 1],
    columns=vocab)
out_matr

,,a,b,c,d,e,f,g,h,i,...,q,r,s,t,u,v,w,x,y,z
0,0.001256,0.065405,0.016717,0.049512,6.377361e-02,0.096101,0.042055,0.022999,0.015779,0.006397,...,6.969541e-04,0.083962,0.078302,0.150841,0.001192,0.010507,0.019164,0.000200,0.025090,1.393962e-03
1,0.384606,0.066801,0.000014,0.000434,1.933939e-07,0.124496,0.000152,0.000002,0.071215,0.140646,...,3.611434e-08,0.016931,0.000146,0.000544,0.059414,0.000399,0.000004,0.003955,0.000002,6.359881e-15

### Supervised обучение скрытой марковской модели (максимум правдоподобия)

In [10]:
def make_tag(c):
    if c in 'aeiouy':
        return (c, '1')
    else:
        return (c, '0')
supervised = [make_tag(c) for c in text]

In [11]:
tagger = trainer.train_supervised([supervised[:500]])

#### Исследуем полученную модель

Частоты совстречаемостей тегов

In [12]:
for t in tagger._transitions:
    print(t, tagger._transitions[t].__dict__)

0 {'_freqdist': FreqDist({'0': 177, '1': 152})}
1 {'_freqdist': FreqDist({'0': 152, '1': 18})}

Матрица переходов $$\{a_{ij} = p(s_j|s_i)\}_{i,j = 1}^{|S|}$$

In [13]:
trans_matr = pd.DataFrame(
    data=np.array([
        [tagger._transitions['0'].prob('0'), tagger._transitions['0'].prob('1')],
        [tagger._transitions['1'].prob('0'), tagger._transitions['1'].prob('1')]
    ]),
    columns=[0, 1],
    index=[0, 1])
trans_matr

          0         1
0  0.537994  0.462006
1  0.894118  0.105882

Матрица выходных вероятностей $$\{ b_{ij} = p(x_j|s_i) \}_{i, j = 1}^{|S|, |X|}$$

In [14]:
out_matr = pd.DataFrame(
    data=np.array([
        [tagger._outputs['0'].prob(c) for c in vocab],
        [tagger._outputs['1'].prob(c) for c in vocab]
    ]),
    index=[0, 1],
    columns=vocab)
out_matr

,,a,b,c,d,e,f,g,h,i,...,q,r,s,t,u,v,w,x,y,z
0,0.245455,0.000000,0.009091,0.060606,0.051515,0.000000,0.030303,0.024242,0.072727,0.000000,...,0.0,0.1,0.054545,0.133333,0.000000,0.015152,0.018182,0.00303,0.000000,0.0
1,0.000000,0.164706,0.000000,0.000000,0.000000,0.323529,0.000000,0.000000,0.000000,0.194118,...,0.0,0.0,0.000000,0.000000,0.094118,0.000000,0.000000,0.00000,0.070588,0.0

## Языковая модель

Построим языковую модель сначала вручную на простом синтетическом корпусе, затем обучим модель из пакета `nltk` на стихотворении "Дом, который построил Джек"

### Первый пример

In [15]:
text = 'SOS SOS ' + 'А Б ' * 100 + 'EOS'
tokens = text.split()
n = len(tokens)
tokens[:10]

['SOS', 'SOS', 'А', 'Б', 'А', 'Б', 'А', 'Б', 'А', 'Б']

In [16]:
def ngrams_and_prefix_counts(tokens, n_max):
    # словарь n-грамм и их частот
    ngrams_counts = {}
    # словарь n-граммных префиксов и их частот
    prefix_counts = {}

    n = len(tokens)
    for i in range(n_max):
        ngrams_counts[i + 1] = Counter([tuple(tokens[j : j + i + 1]) for j in range(n - i)])
        prefix_counts[i + 1] = Counter([tuple(tokens[j : j + i] + ['*']) for j in range(n - i)])

    return ngrams_counts, prefix_counts

In [17]:
ngram_counts, prefix_counts = ngrams_and_prefix_counts(tokens, 3)

In [18]:
ngram_counts

{1: Counter({('SOS',): 2, ('А',): 100, ('Б',): 100, ('EOS',): 1}),
 2: Counter({('SOS', 'SOS'): 1,
          ('SOS', 'А'): 1,
          ('А', 'Б'): 100,
          ('Б', 'А'): 99,
          ('Б', 'EOS'): 1}),
 3: Counter({('SOS', 'SOS', 'А'): 1,
          ('SOS', 'А', 'Б'): 1,
          ('А', 'Б', 'А'): 99,
          ('Б', 'А', 'Б'): 99,
          ('А', 'Б', 'EOS'): 1})}

In [19]:
prefix_counts

{1: Counter({('*',): 203}),
 2: Counter({('SOS', '*'): 2, ('А', '*'): 100, ('Б', '*'): 100}),
 3: Counter({('SOS', 'SOS', '*'): 1,
          ('SOS', 'А', '*'): 1,
          ('А', 'Б', '*'): 100,
          ('Б', 'А', '*'): 99})}

#### N-граммы и их частотные вероятности

$$\hat p_i = \hat p(w_i)$$

In [20]:
def unigram_probas(ngram_counts):
    p1 = {}
    n = sum(ngram_counts[1].values())
    for w in ngram_counts[1]:
        p1[w] = ngram_counts[1][w] / n
    return p1

In [21]:
p1 = unigram_probas(ngram_counts)
p1

{('SOS',): 0.009852216748768473,
 ('А',): 0.49261083743842365,
 ('Б',): 0.49261083743842365,
 ('EOS',): 0.0049261083743842365}

$$\hat p_{i, i - 1} = \hat p(w_i|w_{i - 1})$$

In [22]:
def bigram_probas(ngram_counts, prefix_counts):
    p2 = {}
    for w in ngram_counts[2]:
        pre_w = tuple([w[0]] + ['*'])
        p2[u'{1}|{0}'.format(*w)] = ngram_counts[2][w] / prefix_counts[2][pre_w]
    return p2

In [23]:
p2 = bigram_probas(ngram_counts, prefix_counts)
p2

{'SOS|SOS': 0.5, 'А|SOS': 0.5, 'Б|А': 1.0, 'А|Б': 0.99, 'EOS|Б': 0.01}

$$\hat p_{i, i - 1, i - 2} = \hat p(w_i|w_{i - 1}, w_{i - 2})$$

In [24]:
def trigram_probas(ngram_counts, prefix_counts):
    p3 = {}
    for w in ngram_counts[3]:
        pre_w = w[:2] + tuple(['*'])
        p3[u'{2}|{1},{0}'.format(*w)] = ngram_counts[3][w] / prefix_counts[3][pre_w]
    return p3

In [25]:
p3 =  trigram_probas(ngram_counts, prefix_counts)
p3

{'А|SOS,SOS': 1.0,
 'Б|А,SOS': 1.0,
 'А|Б,А': 0.99,
 'Б|А,Б': 1.0,
 'EOS|Б,А': 0.01}

#### Проверка гипотезы, что триграммную модель можно свести к биграммной против правосторонней альтернативы

Статистика:
$$-2 \log (\prod_{i, j, k = 1}^m (\hat p_{ij} / \hat p_{ijk})^{n_{ijk}}) = \sum_{i, j, k}^m -2 n_{ijk} \log \hat p_{ij} + 2 n_{ijk} \log \hat p_{ijk} = \sum_{i = 3}^N -2 \log \hat p_{i,i - 1} + 2 \log \hat p_{i, i - 1, i - 2},$$
$$n_{ijk} = |\{X_t: X_t = O_i, X_{t + 1} = O_j, X_{t + 2} = O_k\}|$$

In [26]:
def chi2_statistic(p2, p3, tokens):
    stat2 = []
    stat3 = []
    n = len(tokens)
    for i in range(n - 2):
        w = tokens[i : i + 3]
        ngram3 = '{2}|{1},{0}'.format(*w)
        ngram2 = '{1}|{0}'.format(*w)

        stat2.append(np.log(p2[ngram2]))
        stat3.append(np.log(p3[ngram3]))
    return - 2 * np.sum(stat2) + 2 * np.sum(stat3)

In [27]:
m = len(p3)
stat = chi2_statistic(p2, p3, tokens)

In [28]:
print(f'p-value = {1 - st.distributions.chi2(m * ((m - 1) ** 2) - 1).cdf(stat)}')

p-value = 1.0

### Второй пример

In [29]:
text = 'SOS SOS ' + 'А Б Б А Б А Б А Б Б А А ' * 100
tokens = text.split()
tokens[:10]

['SOS', 'SOS', 'А', 'Б', 'Б', 'А', 'Б', 'А', 'Б', 'А']

In [30]:
ngram_counts, prefix_counts = ngrams_and_prefix_counts(tokens, 3)

In [31]:
ngram_counts

{1: Counter({('SOS',): 2, ('А',): 600, ('Б',): 600}),
 2: Counter({('SOS', 'SOS'): 1,
          ('SOS', 'А'): 1,
          ('А', 'Б'): 400,
          ('Б', 'Б'): 200,
          ('Б', 'А'): 400,
          ('А', 'А'): 199}),
 3: Counter({('SOS', 'SOS', 'А'): 1,
          ('SOS', 'А', 'Б'): 1,
          ('А', 'Б', 'Б'): 200,
          ('Б', 'Б', 'А'): 200,
          ('Б', 'А', 'Б'): 300,
          ('А', 'Б', 'А'): 200,
          ('Б', 'А', 'А'): 100,
          ('А', 'А', 'А'): 99,
          ('А', 'А', 'Б'): 99})}

In [32]:
prefix_counts

{1: Counter({('*',): 1202}),
 2: Counter({('SOS', '*'): 2, ('А', '*'): 599, ('Б', '*'): 600}),
 3: Counter({('SOS', 'SOS', '*'): 1,
          ('SOS', 'А', '*'): 1,
          ('А', 'Б', '*'): 400,
          ('Б', 'Б', '*'): 200,
          ('Б', 'А', '*'): 400,
          ('А', 'А', '*'): 198})}

In [33]:
p1 = unigram_probas(ngram_counts)
p1

{('SOS',): 0.0016638935108153079,
 ('А',): 0.49916805324459235,
 ('Б',): 0.49916805324459235}

In [34]:
p2 = bigram_probas(ngram_counts, prefix_counts)
p2

{'SOS|SOS': 0.5,
 'А|SOS': 0.5,
 'Б|А': 0.667779632721202,
 'Б|Б': 0.3333333333333333,
 'А|Б': 0.6666666666666666,
 'А|А': 0.332220367278798}

In [35]:
p3 =  trigram_probas(ngram_counts, prefix_counts)
p3

{'А|SOS,SOS': 1.0,
 'Б|А,SOS': 1.0,
 'Б|Б,А': 0.5,
 'А|Б,Б': 1.0,
 'Б|А,Б': 0.75,
 'А|Б,А': 0.5,
 'А|А,Б': 0.25,
 'А|А,А': 0.5,
 'Б|А,А': 0.5}

#### Проверка той же гипотезы

In [36]:
stat = chi2_statistic(p2, p3, tokens)

In [37]:
print(f'p-value = {1 - st.distributions.chi2(m * ((m - 1) ** 2) - 1).cdf(stat)}')

p-value = 0.0

#### Сглаживание Лапласа

In [38]:
n1 = list(nltk_ngrams(tokens, 1))
n2 = list(nltk_ngrams(tokens, 2))
n3 = list(nltk_ngrams(tokens, 3))
n3[:10]

[('SOS', 'SOS', 'А'),
 ('SOS', 'А', 'Б'),
 ('А', 'Б', 'Б'),
 ('Б', 'Б', 'А'),
 ('Б', 'А', 'Б'),
 ('А', 'Б', 'А'),
 ('Б', 'А', 'Б'),
 ('А', 'Б', 'А'),
 ('Б', 'А', 'Б'),
 ('А', 'Б', 'Б')]

In [39]:
laplace = lm.Laplace(order=3)
laplace.fit([n1] + [n2] + [n3], vocabulary_text=list(set(tokens)))
regular_lm = lm.MLE(order=3)
regular_lm.fit([n1] + [n2] + [n3], vocabulary_text=list(set(tokens)))

#### Перплексия (Меньше => лучше)

In [40]:
laplace.perplexity(n1), regular_lm.perplexity(n1)

(2.0244297368851374, 2.02243644712183)

In [41]:
foo = [('b'), ('a'), ('r')]
laplace.perplexity(foo), regular_lm.perplexity(foo)

(1206.000000000001, inf)

#### Сглаженная по Лапласу оценка вероятности

$$p_L(w_i) = \frac{c_i + 1}{\sum_{i = 1}^v c_i + v}$$
$$p_L(w_i|w_j) = \frac{c_{ij} + 1}{\sum_{j=1}^v (c_{ij} + 1)} = \frac{c_{ij} + 1}{c_i + v}$$

$$p_L('А'|'SOS')$$

In [42]:
laplace.score('А', context=['SOS']), regular_lm.score('А', context=['SOS'])

(0.3333333333333333, 0.5)

$$p_L('SOS')$$

In [43]:
laplace.score('SOS'), regular_lm.score('SOS')

(0.0024875621890547263, 0.0016638935108153079)

#### n-граммы не встречаючиеся в тексте:

In [44]:
laplace.score('C', context=['SOS']), laplace.score('ыаываа', context=['B']), laplace.score('B')

(0.16666666666666666, 0.25, 0.0008291873963515755)

In [45]:
regular_lm.score('C', context=['SOS']), regular_lm.score('ыаываа', context=['B']), regular_lm.score('B')

(0.0, 0, 0.0)

### Генерация текста

In [46]:
rt = RegexpTokenizer(u'\w+')

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_1607/2635976741.py:1: SyntaxWarning: invalid escape sequence '\w'
  rt = RegexpTokenizer(u'\w+')

In [47]:
with urllib.request.urlopen('https://raw.githubusercontent.com/Intelligent-Systems-Phystech/psad/master/seminars/sem12/data/jack.txt') as f:
    text = f.read().decode().lower()

In [48]:
text[:100]

'\nвот дом,\nкоторый построил джек.\n\nа это пшеница,\nкоторая в тёмном чулане хранится\nв доме,\nкоторый по'

In [49]:
tokens = rt.tokenize(text)
len(tokens), len(set(tokens))

(247, 57)

In [50]:
n1 = list(nltk_ngrams(tokens, 1) )
n2 = list(nltk_ngrams(tokens, 2))
n3 = list(nltk_ngrams(tokens, 3))

In [51]:
laplace = lm.Laplace(order=3)
laplace.fit([n1] + [n2] + [n3], vocabulary_text=list(set(tokens)))

In [52]:
' '.join(laplace.generate(50, random_seed=42))

'птица синица которая часто ворует пшеницу которая в тёмном чулане хранится в доме который построил джек а это старушка седая и строгая которая доит корову безрогую лягнувшую старого пса без хвоста который за шиворот треплет кота который пугает и ловит синицу которая часто ворует пшеницу которая в тёмном чулане хранится'

In [53]:
' '.join(laplace.generate(50, text_seed='вот дом который построил джек'.split(), random_seed=42))

'вот два петуха которые будят того пастуха который бранится с коровницей строгою которая доит корову безрогую лягнувшую старого пса без хвоста который за шиворот треплет кота который пугает и ловит синицу которая часто ворует пшеницу которая в тёмном чулане хранится в доме который построил джек а это корова безрогая лягнувшая'

In [54]:
' '.join(laplace.generate(50, text_seed='привет как дела'.split(), random_seed=42))

'птица синица которая часто ворует пшеницу которая в тёмном чулане хранится в доме который построил джек а это старушка седая и строгая которая доит корову безрогую лягнувшую старого пса без хвоста который за шиворот треплет кота который пугает и ловит синицу которая часто ворует пшеницу которая в тёмном чулане хранится'